name: whereshot
description: "AI-powered photo location detection app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State management
  riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

  # Navigation
  go_router: 15.0.0

  # API & Data
  http: 1.3.0
  dio: 5.8.0+1
  json_annotation: 4.9.0

  # Firebase
  firebase_core: 3.13.0
  firebase_storage: 12.4.5
  cloud_firestore: 5.6.6

  # Image handling
  image_picker: 1.1.2
  cached_network_image: 3.4.1
  image: 4.5.4

  # Maps
  google_maps_flutter: 2.12.1

  # In-app purchases
  purchases_flutter: 8.7.3

  # Storage & Persistence
  shared_preferences: 2.5.3
  path_provider: 2.1.5
  uuid: 4.5.1
  build_runner: 2.4.15
  json_serializable: 6.9.5

  # Environment Variables
  envied: 1.1.1

  # Permissions
  permission_handler: 12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: 2.6.4
  envied_generator: 1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
